apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
- apiGroups:
  - ""  # Core API group
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - list
  - watch
