# templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["list"]
